### ISSUE TITLE
Proposed TRAEFIK_CONTAINER_ID_COMMAND not working for pinned version image

### ISSUE THREAD

**Issue by alexdelprete** [vegardit/docker-traefik-logrotate#11]
My compose config for Traefik:

```yaml
  traefik:
    image: traefik:v2.8.3
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
```

The documented command doesn't find the image:

```yaml
      # command to determine the id of the container running Traefik:
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --quiet --filter ancestor=traefik
```

Had to replace with one of the following:

```yaml
      TRAEFIK_CONTAINER_ID_COMMAND: docker inspect --format="{{.Id}}" traefik
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --no-trunc -aqf "name=^traefik$$"
```

Hope it helps anyone else having with the same issue.
