### ISSUE TITLE
Use socket-protector instead of /var/run/docker.sock

### ISSUE THREAD

**Issue by plague-doctor** [vegardit/docker-traefik-logrotate#16]
It would be nice if we could use a socket-protector like `knrdl/traefik-docker-protector` (or any other) instead of, not too not too secure, ` /var/run/docker.sock`.

Any chance this could be implemented?

**Comment by sebthom** [comment]
You should be able to do so by specifying the `DOCKER_HOST` environment variable for the log rotate container instead of mounting the docker.sock file. something like the following (I haven't tried it though):

```yaml
version: '3.7'

networks:
  services_net:
    external: true

  public_net:
    external: true

  stack_internal:
    attachable: false
    driver: overlay
    driver_opts:
      encrypted: "true"

services:

  protected_docker_socket:
    image: tecnativa/docker-socket-proxy:latest # see https://github.com/Tecnativa/docker-socket-proxy
    networks: [ stack_internal ]
    environment:
      CONTAINERS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw

  logrotate:
    image: vegardit/traefik-logrotate:latest
    volumes:
      - ${STACK_DATA_ROOT}/logs:/var/log/traefik:rw # folder containing access.log file
    environment:
      LOGROTATE_LOGS: "/var/log/traefik/*.log"
      DOCKER_HOST: tcp://protected_docker_socket:2375
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --quiet --filter name=traefik_proxy

  proxy:
    image: traefik:latest
    networks: [ stack_internal, public_net, services_net ]
    ports:
      - 80:80
      - {target: 443, published: 443, protocol: tcp, mode: host } # mode: host is required to get real remote ip in access logs
    volumes:
      - ${STACK_DATA_ROOT}/conf.d/:/conf.d/:ro
      - ${STACK_DATA_ROOT}/logs:/var/log/traefik:rw
      - ${STACK_DATA_ROOT}/traefik.yml:/traefik.yml:ro
      - ${STACK_DATA_ROOT}/keystore.json:/keystore.json # holds self-acquired letsencrypt certs
    labels:
      traefik.enable: "true"
```

If you get it working, please post your config for others as reference. Thanks!
