### ISSUE TITLE
Feature Request: Accept mutiple directories for rotating logs

### ISSUE THREAD

**Issue by fgeck** [vegardit/docker-traefik-logrotate#18]
Hi,

as many people are using traefik + crowdsec or fail2ban I think it would be beneficial to accept multiple directories to do the log rotation.

E.g.:

```
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw # required to send USR1 signal to Traefik after log rotation
      - ./log:/var/log/traefik:rw # folder containing access.log file
      - ../crowdsec/log:/var/log/crowdsec:rw
    environment:
      TZ: "Europe/Berlin"
      LOGROTATE_LOGS: "/var/log/traefik/*.log, /var/loge/crowdsec/*.log"
```
