### ISSUE TITLE
Server restart kills docker-traefik-logrotate and traefik

### ISSUE THREAD

**Issue by adsehgal** [vegardit/docker-traefik-logrotate#19]
Hey, I have been using your container for some time now and it works great! Thank you!! However, I have noticed, if I restart my server, when docker starts up and my containers start, traefik-logrotate exits with error code 143 and traefik exits with code 0. I am able to manually restart both containers without issues, but this is consistent across two servers. Any ideas what might be going wrong?

My compose for your container is:
```
  traefik-logrotate:
    image: vegardit/traefik-logrotate:latest
    container_name: traefik-logrotate
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw # required to send USR1 signal to Traefik after log rotation
      - ./data/logs:/var/log/traefik:rw # folder containing access.log file
    environment:
      TZ: "Asia/Kolkata"
      # all environment variables are optional and show the default values:
      LOGROTATE_LOGS: "/var/log/traefik/*.log" # log files to rotate, directory must match volume mount
      LOGROTATE_TRIGGER_INTERVAL: daily  # rotate daily, must be one of: daily, weekly, monthly, yearly
      LOGROTATE_TRIGGER_SIZE: 50M        # rotate if log file size reaches 50MB
      LOGROTATE_MAX_BACKUPS: 2          # keep 14 backup copies per rotated log file
      LOGROTATE_START_INDEX: 1           # first rotated file is called access.1.log
      LOGROTATE_FILE_MODE: 0644          # file mode of the rotated file
      LOGROTATE_FILE_USER: root          # owning user of the rotated file
      LOGROTATE_FILE_GROUP: root         # owning group of the rotated file
      CRON_SCHEDULE: "0 0 * * *"          # run every day at 12:00AM
      CRON_LOG_LEVEL: 5                  # see https://unix.stackexchange.com/a/414010/378036
      # command to determine the id of the container running Traefik:
      TRAEFIK_CONTAINER_ID_COMMAND: docker ps --no-trunc --quiet --filter label=org.opencontainers.image.title=Traefik
```
